export const the_climbs = [
  { url: 'theclimb_sillim', name: 'the_climb_sillim', ko: '신림' },
  { url: 'theclimb_sinsa', name: 'the_climb_sinsa', ko: '신사' },
  { url: 'theclimb_magok', name: 'the_climb_magok', ko: '마곡' },
  { url: 'theclimb_sadang', name: 'the_climb_sadang', ko: '사당' },
  { url: 'theclimb_snu', name: 'the_climb_snu', ko: '서울대' },
  { url: 'theclimb_ilsan', name: 'the_climb_ilsan', ko: '일산' },
  { url: 'theclimb_yeonnam', name: 'the_climb_yeonnam', ko: '연남' },
  { url: 'theclimb_b_hongdae', name: 'the_climb_b_hongdae', ko: '홍대' },
  { url: 'theclimb_mullae', name: 'the_climb_mullae', ko: '문래' },
  { url: 'theclimb_isu', name: 'the_climb_isu', ko: '이수' },
  { url: 'theclimb_yangjae', name: 'the_climb_yangjae', ko: '양재' },
  { url: 'theclimb_gangnam', name: 'the_climb_gangnam', ko: '강남' },
  { url: 'theclimb_seongsu', name: 'the_climb_seongsu', ko: '성수' },
  { url: 'theclimb_nonhyeon', name: 'the_climb_nonhyeon', ko: '논현' },
]
