create table "public"."climbing" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null
);


alter table "public"."climbing" enable row level security;

create table "public"."climbing_branch" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "branch" character varying,
    "logo" text
);


alter table "public"."climbing_branch" enable row level security;

CREATE UNIQUE INDEX climbing_branch_pkey ON public.climbing_branch USING btree (id);

CREATE UNIQUE INDEX climbing_name_key ON public.climbing USING btree (name);

CREATE UNIQUE INDEX climbing_pkey ON public.climbing USING btree (id);

alter table "public"."climbing" add constraint "climbing_pkey" PRIMARY KEY using index "climbing_pkey";

alter table "public"."climbing_branch" add constraint "climbing_branch_pkey" PRIMARY KEY using index "climbing_branch_pkey";

alter table "public"."climbing" add constraint "climbing_name_key" UNIQUE using index "climbing_name_key";

alter table "public"."climbing_branch" add constraint "climbing_branch_branch_fkey" FOREIGN KEY (branch) REFERENCES climbing(name) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."climbing_branch" validate constraint "climbing_branch_branch_fkey";

grant delete on table "public"."climbing" to "anon";

grant insert on table "public"."climbing" to "anon";

grant references on table "public"."climbing" to "anon";

grant select on table "public"."climbing" to "anon";

grant trigger on table "public"."climbing" to "anon";

grant truncate on table "public"."climbing" to "anon";

grant update on table "public"."climbing" to "anon";

grant delete on table "public"."climbing" to "authenticated";

grant insert on table "public"."climbing" to "authenticated";

grant references on table "public"."climbing" to "authenticated";

grant select on table "public"."climbing" to "authenticated";

grant trigger on table "public"."climbing" to "authenticated";

grant truncate on table "public"."climbing" to "authenticated";

grant update on table "public"."climbing" to "authenticated";

grant delete on table "public"."climbing" to "service_role";

grant insert on table "public"."climbing" to "service_role";

grant references on table "public"."climbing" to "service_role";

grant select on table "public"."climbing" to "service_role";

grant trigger on table "public"."climbing" to "service_role";

grant truncate on table "public"."climbing" to "service_role";

grant update on table "public"."climbing" to "service_role";

grant delete on table "public"."climbing_branch" to "anon";

grant insert on table "public"."climbing_branch" to "anon";

grant references on table "public"."climbing_branch" to "anon";

grant select on table "public"."climbing_branch" to "anon";

grant trigger on table "public"."climbing_branch" to "anon";

grant truncate on table "public"."climbing_branch" to "anon";

grant update on table "public"."climbing_branch" to "anon";

grant delete on table "public"."climbing_branch" to "authenticated";

grant insert on table "public"."climbing_branch" to "authenticated";

grant references on table "public"."climbing_branch" to "authenticated";

grant select on table "public"."climbing_branch" to "authenticated";

grant trigger on table "public"."climbing_branch" to "authenticated";

grant truncate on table "public"."climbing_branch" to "authenticated";

grant update on table "public"."climbing_branch" to "authenticated";

grant delete on table "public"."climbing_branch" to "service_role";

grant insert on table "public"."climbing_branch" to "service_role";

grant references on table "public"."climbing_branch" to "service_role";

grant select on table "public"."climbing_branch" to "service_role";

grant trigger on table "public"."climbing_branch" to "service_role";

grant truncate on table "public"."climbing_branch" to "service_role";

grant update on table "public"."climbing_branch" to "service_role";


